<footer class="footer">
    <div class="footer_top">
        <div class="footer_col_wrapper clearfix">
            <div class="col_footer col_footer_nav">
                <h4><?php echo $this->localize('quickLinks'); ?></h4>
                <ul class="nav_footer">
                    <?php foreach ($this->footerMenu as $item) : ?>
                        <li><a href="<?php echo $item['url']; ?>"><?php echo $item['title']; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="col_footer col_footer_contact">
                <h4><?php echo $this->localize('contacts'); ?></h4>
     <span class="name">
       <?php echo $this->contacts['name']; ?>
     </span>
     <span class="tel">
       <?php echo $this->contacts['phone_1']; ?>
       <?php echo $this->contacts['phone_2']; ?>
       <?php echo $this->contacts['phone_3']; ?>
     </span>
                <a class="email"
                   href="mailto:<?php echo $this->contacts['email_1']; ?>"><?php echo $this->contacts['email_1']; ?></a>
				<div itemscope itemtype="http://schema.org/Organization">
				<span itemprop="addressLocality">Симферополь,</span>
				<span itemprop="streetAddress">Проспект Победы, 82</span>
				</div>
            </div>
            <div class="social-block col_footer col_footer_social">
                <h4 class="read-us-footer">Читайте нас:</h4>
                <a href="https://www.facebook.com/useful.des" rel="nofollow"><div class="social-icon facebook">&nbsp;</div></a>
                <a href="https://vk.com/kucherenkoaleksandra_designer" rel="nofollow"><div class="social-icon vk">&nbsp;</div></a>
                <a href="https://twitter.com/Sasha_klima" rel="nofollow"><div class="social-icon tweet">&nbsp;</div></a>
            </div>
            <div id="twit-block" style="display: none" class="col_footer col_footer_social">
                <h4><?php echo $this->localize('lastSocialActive'); ?></h4>

                <p>
                    <span id="twit-text"></span>
                    <?php echo $this->localize('from'); ?>
                    <a id="twit-link" target="_blank"></a>
                </p>
            </div>
        </div>
    </div>
    <div class="footer_bottom">
        <p class="copyright">
            Copyright &copy; <?php echo date('Y', time()); ?>. Kucherenko Design
        </p>
    </div>
</footer>