<header class="header">
    <div class="header_top_wrapper">
        <div class="header_top clearfix">
            <div class="btn_language">
                <a class="btn btn_en <?php echo ($this->currentLang == 'en') ? '' : 'active'?>" href="/site/lang?lang=en&page=<?php echo $this->currentUrl; ?>">en</a>
                <a class="btn btn_ru <?php echo ($this->currentLang == 'ru') ? '' : 'active'?>" href="/site/lang?lang=ru&page=<?php echo $this->currentUrl; ?>">ru</a>
            </div>
            <?php echo $this->partial('nav', ['menu' => $this->menu]); ?>
        </div>
    </div>
    <div class="header_bottom">
        <div class="contact_block">
            <a class="btn btn_blue" href="<?php echo $this->menu['contacts']['url']; ?>"><?php echo $this->localize('contactAndOrderDesign'); ?></a>
            <div itemscope itemtype="http://schema.org/Organization">
                <span itemprop="telephone" class="tell_item"><?php echo $this->contacts['phone_1']; ?></span>
                <span itemprop="telephone" class="tell_item"><?php echo $this->contacts['phone_2']; ?></span>
				<time itemprop="openingHours" datetime="Mo-Fr 9:00−18:00">Звоните пн-пт с 9:00 до 18:00 </time>
            </div>
        </div>
        <div class="logo">
            <a href="/"><img src="<?php echo $this->baseUrl; ?>/images/logo@2x.png" alt="logo"/></a>
        </div>
        <div class="text_block">
            <p><?php echo $this->aboutPreview; ?></p>
            <a class="btn btn_more" href="<?php echo $this->menu['about']['url']; ?>"><?php echo $this->localize('readMore'); ?></a>
        </div>
    </div>
</header>