<form class="sr-box" method="post" action="https://smartresponder.ru/subscribe.html" target="_blank" name="SR_form_280569_63">
    <label class="f-item f-item_text">
        <input type="text" name="field_name_first" placeholder="<?php echo $this->localize('yourName'); ?>" />
    </label>
    <label class="f-item f-item_email">
        <input type="text" name="field_email" class="sr-required" placeholder="<?php echo $this->localize('yourEmail'); ?>" />
    </label>
    <button class="btn btn_blue" type="submit"><?php echo $this->localize('subscribe'); ?></button>
    <input type="hidden" name="uid" value="602604">
    <input type="hidden" name="did[]" value="728068"><input type="hidden" name="tid" value="0" />
    <input type="hidden" name="lang" value="ru">
    <input name="script_url_280569_63" type="hidden"value="https://imgs.smartresponder.ru/on/6e7d54aeeac42d70e634c580f2d1395c1a8959f2/283267_81">

    <div class="b-social">
        <div class="twitter_follow">
            <a href="https://twitter.com/Sasha_klima" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @Sasha_klima</a>
        </div>
        <div class="fb-like" data-href="https://kucherenko-design.ru/" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>

    </div>
</form>
<div class="link_social">
    <a target="_blank" href="https://www.behance.net/kucherenko_aleks" class="item_behance">behance</a>
    <a target="_blank" href="https://www.linkedin.com/profile/view?id=204385824&authType=NAME_SEARCH&authToken=5kJD&locale=ru_RU&trk=tyah&trkInfo=tarId%3A1407507848183%2Ctas%3Aкучеренко%20александра%2Cidx%3A1-1-1" class="item_linkedin">linkedin</a>
</div>

<script type="text/javascript" src="https://imgs.smartresponder.ru/52568378bec6f68117c48f2f786db466014ee5a0/"></script>
<script type="text/javascript">
    _sr(function () {
        _sr('form[name="SR_form_280569_63"]').find('div#sr-preload_').prop('id', 'sr-preload_280569_63');
        _sr('#sr-preload_280569_63').css({'width': parseInt(_sr('form[name="SR_form_280569_63"]').width() + 'px'), 'height': parseInt(_sr('form[name="SR_form_280569_63"]').height()) + 'px', 'line-height': parseInt(_sr('form[name="SR_form_280569_63"]').height()) + 'px'}).show();
        if (_sr('form[name="SR_form_280569_63"]').find('input[name="script_url_280569_63"]').length) {
            _sr.ajax({
                url: _sr('input[name="script_url_280569_63"]').val() + '/' + (typeof document.charset !== 'undefined' ? document.charset : document.characterSet),
                dataType: "script",
                success: function () {
                    _sr('#sr-preload_280569_63').hide();
                }
            });
        }
    });
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&appId=207671115966935&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>