<h1>Interior design</h1>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Sort</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->designs as $interior) : ?>
            <tr>
                <td><?php echo $interior['title']; ?> | <?php echo $interior['title_en']; ?></td>
                <td><?php echo $interior['status'] == true ? 'enabled' : 'disabled' ?></td>
                <td><?php echo $interior['sortorder']?></td>
                <td>
                    <a href="/admin/design/edit?id=<?php echo $interior['id']; ?>" class="btn btn-primary">edit</a>
                    <a href="/admin/design/delete?id=<?php echo $interior['id']; ?>" class="btn btn-danger" <?php echo ($interior['canDelete'] == false) ? 'disabled="disabled"' : ''; ?> >delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <form action="/admin/design/create" method="post">
            <button type="submit" class="btn btn-primary">Add category</button>
        </form>
    </div>
</div>