<h1>Press</h1>
<a href="/admin/press" class="btn btn-primary">Back to list</a>
<div class="row">
    <form action="/admin/press/edit?id=<?php echo $this->data['id']; ?>" method="post" enctype="multipart/form-data">
    <div class="col-md-6">
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="1"
                           name="status" <?php echo ($this->data['status'] == 1) ? 'checked="checked"' : '' ?>>
                    Status visible
                </label>
            </div>
            <div class="date-input">
                <label>Date</label>

                <input type="text" class="form-control" name="date" value="<?php echo $this->data['date']; ?>">
            </div> 

            <div class="form-group form-horizontal">
                <label>Url</label>
                <input name="url" type="text" value="<?php echo $this->data['url']; ?>" class="form-control">
            </div>        

            <div class="form-group form-horizontal">
                <label>Category</label>

                <select name="category" class="form-control">

                    <?php foreach ($this->select as $optKey => $optVal) :?>
                        <option <?php echo ($optVal == $this->data['category']) ? 'selected="selected"' : '';?> value="<?php echo $optKey; ?>"><?php echo $optVal; ?></option>
                    <?php endforeach; ?>

                </select>
            </div>        

        <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#tab_ru" role="tab" data-toggle="tab">ru</a></li>
            <li><a href="#tab_en" role="tab" data-toggle="tab">en</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="tab_ru">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" class="form-control" name="title" value="<?php echo $this->data['title']; ?>">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>
                    <textarea name="text" class="form-control" rows="6"><?php echo $this->data['text']; ?></textarea>
                </div>
                <div class="form-group form-horizontal">
                    <label>Meta keywords</label>
                    <input name="meta_keywords" type="text" value="<?php echo $this->data['meta_keywords']; ?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Meta description</label>
                    <input name="meta_description" type="text" value="<?php echo $this->data['meta_description']; ?>" class="form-control">
                </div>
                

            </div>
            <div class="tab-pane" id="tab_en">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" name="title_en" value="<?php echo $this->data['title_en']; ?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>
                    <textarea name="text_en" class="form-control" rows="6"><?php echo $this->data['text_en']; ?></textarea>
                </div>
                <div class="form-group form-horizontal">
                    <label>Meta keywords</label>
                    <input name="meta_keywords_en" type="text" value="<?php echo $this->data['meta_keywords_en']; ?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Meta description</label>
                    <input name="meta_description_en" type="text" value="<?php echo $this->data['meta_description_en']; ?>" class="form-control">
                </div>                
            </div>
                            
        </div>

    </div>
    <div class="col-md-6">
        <div class="images_download_thumbnail clearfix">
                <div class="form-group form-horizontal">
                    <label>Upload images</label>

                    <input type="file" name="image_1" class="form-control">
                    <?php if (!empty($this->data['img_des'])) :?>
                    <div class="image_thumbnail">
                        <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->data['img_des']; ?>" alt="img"/>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="form-group form-horizontal">
                    <label>Upload images</label>

                    <input type="file" name="image_2" class="form-control">
                    <?php if (!empty($this->data['img_des'])) :?>
                    <div class="image_thumbnail">
                        <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->data['img_2_des']; ?>" alt="img"/>
                    </div>
                    <?php endif; ?>
                </div>
        </div>
    </div>
    <div class="clearfix btn-wrapper">
        <button type="submit" class="btn btn-primary pull-left">Save</button>
    </div>
        </form>
</div>