<script type="text/javascript" src="/js/rusLat.js"></script>
<script type="text/javascript" src="/js/autoRusLat.js"></script>
<h1>Finished projects</h1>
<a href="/admin/projects" class="btn btn-primary clearfix" >Back to list</a>
<div class="row">
<form action="/admin/projects/edit?id=<?php echo $this->data['id']; ?>" method="post" enctype="multipart/form-data">
<div class="col-md-4">
        <div class="checkbox">
            <label>
                <input value="1"
                       name="status" <?php echo ($this->data['status'] == 1) ? 'checked="checked"' : '' ?>
                       type="checkbox">
                Status visible
            </label>
        </div>
    <div class="form-group form-horizontal">
        <label>Category</label>
        <select name="category" class="form-control">
            <?php foreach ($this->select as $optKey => $optVal) :?>
                <option <?php echo ($optKey == $this->data['category']) ? 'selected="selected"' : '';?> value="<?php echo $optKey; ?>"><?php echo $optVal; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group form-horizontal">
        <label>Url</label>
        <input name="url" type="text" value="<?php echo $this->data['url']; ?>" class="form-control">
    </div>
    <ul role="tablist" class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" role="tab" href="#tab_ru_1">ru</a></li>
        <li><a data-toggle="tab" role="tab" href="#tab_en_1">en</a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div id="tab_ru_1" class="tab-pane active">
            <div class="form-group form-horizontal">
                <label>Title</label>
                <input data-action="translate" data-target="url" type="text" name="title" value="<?php echo $this->data['title']; ?>" class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>Meta keywords</label>
                <input name="meta_keywords" type="text" value="<?php echo $this->data['meta_keywords']; ?>" class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>Meta description</label>
                <input name="meta_description" type="text" value="<?php echo $this->data['meta_description']; ?>" class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>City</label>
                <input type="text" name="city" value="<?php echo $this->data['city']; ?>" class="form-control">
            </div>
        </div>
        <div id="tab_en_1" class="tab-pane">
            <div class="form-group form-horizontal">
                <label>Title</label>
                <input type="text" name="title_en" value="<?php echo $this->data['title_en']; ?>"
                       class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>Meta keywords</label>
                <input name="meta_keywords_en" type="text" value="<?php echo $this->data['meta_keywords_en']; ?>" class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>Meta description</label>
                <input name="meta_description_en" type="text" value="<?php echo $this->data['meta_description_en']; ?>" class="form-control">
            </div>
            <div class="form-group form-horizontal">
                <label>City</label>
                <input type="text" name="city_en" value="<?php echo $this->data['city_en']; ?>" class="form-control">
            </div>
        </div>
    </div>
</div>
<div class="col-md-8" class="jImagesContaier">
    <?php foreach ($this->data['items'] as $index => $item) :?>
        <div class="item-project clearfix" class="jImageItem">
            <div class="col-md-50">
                <ul role="tablist" class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" role="tab" href="#tab_ru_<?php echo $index + 2; ?>">ru</a></li>
                    <li><a data-toggle="tab" role="tab" href="#tab_en_<?php echo $index + 2; ?>">en</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="tab_ru_<?php echo $index + 2; ?>" class="tab-pane active">
                        <div class="form-group form-horizontal">
                            <label>Title</label>

                            <input name="items[<?php echo $item['id']; ?>][title]" value="<?php echo $item['title']; ?>" type="text"
                                   class="form-control">
                        </div>
                        <div class="form-group form-horizontal">
                            <label>Description</label>

                            <textarea name="items[<?php echo $item['id']; ?>][text]" rows="3" class="form-control"><?php echo $item['text'] ?></textarea>
                        </div>
                    </div>
                    <div id="tab_en_<?php echo $index + 2; ?>" class="tab-pane">

                        <div class="form-group form-horizontal">
                            <label>Title</label>

                            <input type="text" name="items[<?php echo $item['id']; ?>][title_en]"
                                   value="<?php echo $item['title_en']; ?>" class="form-control">
                        </div>
                        <div class="form-group form-horizontal">
                            <label>Description</label>

                            <textarea name="items[<?php echo $item['id']; ?>][text_en]" rows="3"
                                      class="form-control"><?php echo $item['text_en'] ?></textarea>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-50 image-wrapper">
                <div class="form-group form-horizontal">
                    <label>Upload images (Min width of image is <?php echo $this->minWidth ?> px)</label>
                    <a href="#" class="deleteImage" data-item-id="<?php echo $item['id']; ?>">Delete</a>
                    <input type="file" name="image_<?php echo $item['id']; ?>" class="form-control">

                    <?php if (!empty($item['img_des'])) :?>
                        <div class="image_thumbnail">
                            <img alt="img"
                                 src="<?php echo $this->baseUrl; ?>/<?php echo $item['img_des'] . '?' . time(); ?>">
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <a href="#" id="addMoreImage" data-project-id="<?php echo $this->data['id']; ?>" class="btn btn-primary clearfix">Add more images</a>
</div>
<button class="btn btn-primary clearfix" type="submit">Save</button>
</form>
</div>
<script>
    $('#addMoreImage').click(function(e) {
        e.preventDefault();
        var projectId = $(this).data('project-id');
        $.ajax({
            url: '/api/create-image-item',
            method: 'post',
            dataType: 'json',
            data: {
                project: projectId
            },
            success: function(responce) {
               if (responce.status) {
                   location.reload();
               }
            }
        });

    });
    $('.deleteImage').click(function(e) {
        e.preventDefault();
        var itemId = $(this).data('item-id');
        $.ajax({
            url: '/api/delete-image-item',
            method: 'post',
            dataType: 'json',
            data: {
                id: itemId
            },
            success: function(responce) {
                if (responce.status) {
                    location.reload();
                }
            }
        });

    });
</script>
