<div class="b-content_about">
    <div class="title_content clearfix">
        <h1><?php echo $this->page['title']; ?></h1>
    </div>

    <div class="user_info_wrapper">
        <div class="user_image">
            <img src="<?php echo $this->baseUrl; ?>/images/alexandra-kucherenko-1.jpg" alt="user_img"/>
        </div>
        <div class="user_info">
            <span><?php echo $this->contacts['name']; ?></span>
            <span><?php echo nl2br($this->contacts['who']); ?></span>
        </div>
    </div>
    <div class="content-text">
        <?php echo $this->page['text']; ?>
    <figure class="image">
        <a href="<?php echo $this->baseUrl; ?>/images/tmp/img_about_1.jpg" class="fancybox"><img src="<?php echo $this->baseUrl; ?>/images/tmp/img_about_1.jpg" alt="img"/></a>
    </figure>
    <figure class="image">
        <a href="<?php echo $this->baseUrl; ?>/images/tmp/img_about_2.jpg" class="fancybox"><img src="<?php echo $this->baseUrl; ?>/images/tmp/img_about_2.jpg" alt="img"/></a>
    </figure>        
    </div>

</div>