<div class="b-contact_wrapper clearfix">
    <div class="title_content clearfix">
        <h1><?php echo $this->page['title']; ?></h1>
		<p>Чтобы заказать дизайн интерьера своего помещения, заполните форму или свяжитесь с нами по указанным контактам.</p>
    </div>
    <div class="b-contact_info">
        <h2><?php echo $this->contacts['name']; ?></h2>
		<p class="tell"><?php echo $this->contacts['phone_1']; ?></p>
		<p class="tell"><?php echo $this->contacts['phone_2']; ?></p>
		<p class="tell"><?php echo $this->contacts['phone_3']; ?></p>
		<p>Звоните пн-пт с 9:00 до 18:00</p>
        <p><?php echo $this->contacts['email_1']; ?></p>
		<div class="mark smp active"><p>г. Симферополь, ул. Зои Жильцовой, 15</p></div>
		<div class="mark msk"><p>г. Москва, ул. Маршала Маликовского, д. 6, корпус 1</p></div>
    </div>
    <div class="form_wrapper form_contact">
	<h2>Напишите нам сейчас:</h2>
        <form action="<?php echo $this->baseUrl; ?><?php echo $this->langUrl('/contacts.html'); ?>" method="post" class="clearfix">
            <input name="email" style="display: none" />
            <input name="hash" value="<?php echo $this->hash; ?>" type="hidden" />
            <label class="f-item f-item_text">
                <input name="name" class="f-text f-text_name" type="text" placeholder="<?php echo $this->localize('yourName'); ?>"/>
            </label>
            <label class="f-item f-item_text">
                <input name="contact" class="f-text" type="text" placeholder="<?php echo $this->localize('yourMail'); ?>"/>
            </label>
            <label class="f-item f-item_text">
                <input name="phone" class="f-text" type="text" placeholder="<?php echo $this->localize('yourPhone'); ?>"/>
            </label>
            <label class="f-item f-item_textarea">
                <textarea name="text" class="f-textarea" placeholder="<?php echo $this->localize('message'); ?>" cols="30" rows="10"></textarea>
            </label>
            <button type="submit" class="btn btn_blue"><?php echo $this->localize('send'); ?></button>
        </form>
    </div>
</div>


<div id="tabs">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="smp" class="active"><a href="#smp" data-tabid="smp" role="tab" data-toggle="tab">Симферополь</a></li>
    <li role="msk"><a href="#msk" data-tabid="msk" role="tab" data-toggle="tab">Москва</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="smp">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ab751c3e1f617e2eb4289b2efc97fc3bf13a581880d12312258fb4aae9860290d&amp;width=100%25&amp;height=360&amp;lang=ru_RU&amp;scroll=true"></script>
    </div>
    <div role="tabpanel" class="tab-pane" id="msk">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A7ef8599a5fc26ac311e4b50a75b260a1a55c67f7d3d08c80872bd632ae734637&amp;width=100%25&amp;height=360&amp;lang=ru_RU&amp;scroll=true"></script>
    </div>
  </div>

</div>

<style>
    .mark {
        position: relative;
    }
    .mark.active {
        color: #33b5e7;
    }
    .mark.active::before {
        content: " ";
        background: url(/images/map-pin.png) no-repeat;
        background-size: contain;
/*        height: 20px;*/
/*        border: 1px solid;*/
        position: absolute;
        left: -20px;
        width: 20px;
        height: 20px;
    }
    .tab-pane:not(.active) {
        display: none;
    }
    .nav-tabs {
        padding: 0;
        margin-bottom: 2px;
    }
    .nav-tabs li a {
        padding: 10px;
        color: #fff;
    }
    .nav-tabs li {
        background:rgb(195,195,195);
    }
    .nav-tabs li.active {
        background: #3da9d3;
    }
    
</style>