<div class="b-home_gallery clearfix">
    <div class="image_wrapper image_wrapper_x2">
        <figure class="image">
            <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->gallery[0]['img_des']; ?>" alt="image"/>
        </figure>
        <div class="content_image">
            <div class="title_content">
                <h1><?php echo $this->gallery[0]['title']; ?></h1>
            </div>
            <div class="text_content">
                <p><?php echo $this->gallery[0]['text']; ?></p>
            </div>
        </div>
    </div>
    <div class="image_wrapper">
        <figure class="image">
            <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->gallery[1]['img_des']; ?>" alt="image"/>
        </figure>
        <div class="content_image">
            <div class="title_content">
                <h2><?php echo $this->gallery[1]['title']; ?></h2>
            </div>
            <div class="text_content">
                <p><?php echo $this->gallery[1]['text']; ?></p>
            </div>
        </div>
    </div>
    <div class="image_wrapper">
        <figure class="image">
            <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->gallery[2]['img_des']; ?>" alt="image"/>
        </figure>
        <div class="content_image">
            <div class="title_content">
                <h2><?php echo $this->gallery[2]['title']; ?></h2>
            </div>
            <div class="text_content">
                <p><?php echo $this->gallery[2]['text']; ?></p>
            </div>
        </div>
    </div>
    <div class="image_wrapper image_wrapper_x">
        <figure class="image">
            <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->gallery[3]['img_des']; ?>" alt="image"/>
        </figure>
        <div class="content_image">
            <div class="title_content">
                <h2><?php echo $this->gallery[3]['title']; ?></h2>
            </div>
            <div class="text_content">
                <p><?php echo $this->gallery[3]['text']; ?></p>
            </div>
        </div>
    </div>
    <div class="image_wrapper">
        <figure class="image">
            <img src="<?php echo $this->baseUrl; ?>/<?php echo $this->gallery[4]['img_des']; ?>" alt="image"/>
        </figure>
        <div class="content_image">
            <div class="title_content">
                <h2><?php echo $this->gallery[4]['title']; ?></h2>
            </div>
            <div class="text_content">
                <p><?php echo $this->gallery[4]['text']; ?></p>
            </div>
        </div>
    </div>
</div>
<div class="b-content_bottom clearfix">
    <div class="b-subscribe_info">
        <h3><?php echo $this->localize('receiveNew'); ?></h3>

        <p><?php echo $this->localize('noSpamJust'); ?></p>
    </div>
    <div class="form_wrapper form_subscribe">
        <?php echo $this->partial('subscribe', ['baseUrl' => $this->baseUrl,]); ?>
    </div>
</div>