<div class="b-content_press">
    <div class="categories">
        <?php   
            foreach($this->categories as $category) { ?>
                <?php if ($category['url'] == $this->category_this['full_url']) : ?>
                    <div class="category active"><?php echo $category['title'] ?></div>
                <?php else : ?>
                    <div class="category"><a href="<?php echo $this->baseUrl; ?>/<?php echo $category['url']; ?>"><?php echo $category['title'] ?></a></div>
                <?php endif;?>                
         
            <?php } 
        ?>
    </div>    
    
    <div class="title_content clearfix">
        <h1><?php
            if(isset($this->category_this['h1'])) {
                echo $this->category_this['h1'];
            } 
            else {
                echo $this->page['title'];
            } ?>
        </h1>
    </div>
    
    <?php //echo $this->partial('breadcrumbs')?>

    <div class="press_list">
        <?php foreach ($this->list as $press) :?>
        <div class="item_press clearfix">
            <figure class="images">
                <?php if (!empty($press['img_des'])) :?>
                <a class="fancybox" rel="group1" href="<?php echo $this->baseUrl; ?>/<?php echo $press['img_des']; ?>">
                    <img src="<?php echo $this->baseUrl; ?>/<?php echo $press['img_tmb']; ?>" alt="img" />
                </a>
                <?php endif; ?>
            </figure>
            <div class="item_text">
                <h4><a class="" href="<?php echo $this->langUrl('/press/' . $press['id'].'-'.$press['url'].'.html'); ?>"><?php echo $press['title']; ?></a></h4>
                <p><?php echo $press['date']; ?></p>
                <p><?php echo $press['text']; ?></p>
                <p> <a class="btn btn_more" href="<?php echo $this->langUrl('/press/' . $press['id'].'-'.$press['url'].'.html'); ?>"><?php echo $this->localize('readMore'); ?></a></p>
                
            </div>
        </div>
        <?php endforeach; ?>
        
        <?php if (count($this->pages) > 1) :?>
            <div class="page_pager clearfix">
                <ul class="pager_list">
                    <?php foreach ($this->pages as $page => $link) :?>                    
                        <?php if ($page == $this->page_current) : ?>
                            <li class="pager_item"><span><?php echo $page ?></span></li>
                        <?php else : ?>
                            <li class="pager_item"><a href="<?php echo $link ?>"><?php echo $page ?></a></li>
                            <?php endif;?>
                    <?php endforeach; ?>

                </ul>
            </div>
        <?php endif; ?>
        
    </div>
</div>