<?php /** @var $this \Base\View\View */?>
<div class="b-content_finish_one">
    <?php echo $this->partial('breadcrumbs')?>

    <div class="title_content clearfix">
        <h1><?php echo $this->project['title']; ?></h1>
        <span class="city"><?php echo $this->project['city']; ?></span>
    </div>

    <div class="finish_list">
    <?php foreach($this->project['items'] as $item) :?>
        <div class="item_finish_one">
            <div class="item_title">
                <h2><?php echo $item['title']; ?></h2>
            </div>
            <div class="image_wrapper">
                <figure class="image">
                    <img src="<?php echo $this->baseUrl . '/' . $item['img_org']; ?>" alt="img"/>
                </figure>
                <p><?php echo $item['text']; ?></p>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="project_socials">
    <div class="project_share_txt">
        Понравился проект? Поделись с друзьями:
    </div>
    <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
    <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,gplus,twitter,linkedin,lj" data-counter=""></div>
</div>
    

