<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Admin panel</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/style.css"/>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/jquery-1.11.1.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/wysihtml5-0.3.0.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/admin-js.js"></script>
</head>
<body>
<header class="header">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"  target="_blank" href="/">KUCHERENKO DESIGN</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo ('main' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/main">Main</a></li>
                    <li class="<?php echo ('gallery' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/gallery">Gallery</a></li>
                    <li class="<?php echo ('pages' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/pages">Pages</a></li>
                    <li class="<?php echo ('contacts' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/contacts">Contacts</a></li>
                    <li class="<?php echo ('design' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/design">Designs</a></li>
                    <li class="<?php echo ('projects' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/projects">Projects</a></li>
                    <li class="<?php echo ('services' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/services">Services</a></li>
                    <li class="<?php echo ('presscat' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/presscat">Press Categories</a></li>
                    <li class="<?php echo ('press' == $this->currentPage) ? 'active' : ''?>"><a href="/admin/press">Press</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/admin/auth/logout">logout</a></li>
                </ul>
            </div>
            <!-- /.nav-collapse -->
        </div>
        <!-- /.container -->
    </div>
</header>

<div class="container container_page">
    <?php echo $this->content; ?>
</div>
</body>
</html>