<h1>Services</h1>
<form action="/admin/services" method="post">
<div class="row">
    <div class="col-md-4">
        <h3>Column 1</h3>
        <ul role="tablist" class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" role="tab" href="#tab_ru_1">ru</a></li>
            <li><a data-toggle="tab" role="tab" href="#tab_en_1">en</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div id="tab_ru_1" class="tab-pane active">
                <div class="form-group form-horizontal">
                    <label>Title</label>
                    <input type="text" name="data[1][step_title]" value="<?php echo $this->data[0]['step_title']?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>
                    <textarea name="data[1][step_text]" rows="3" class="form-control"><?php echo $this->data[0]['step_text']?></textarea>
                </div>
            </div>
            <div id="tab_en_1" class="tab-pane">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" name="data[1][step_title_en]" value="<?php echo $this->data[0]['step_title_en']?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>
                    <textarea name="data[1][step_text_en]" rows="3" class="form-control"><?php echo $this->data[0]['step_text_en']?></textarea>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-4">
        <h3>Column 2</h3>

        <ul role="tablist" class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" role="tab" href="#tab_ru_2">ru</a></li>
            <li><a data-toggle="tab" role="tab" href="#tab_en_2">en</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div id="tab_ru_2" class="tab-pane active">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" name="data[2][step_title]" value="<?php echo $this->data[1]['step_title']?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>

                    <textarea name="data[2][step_text]" rows="3" class="form-control"><?php echo $this->data[1]['step_text']?></textarea>
                </div>
            </div>
            <div id="tab_en_2" class="tab-pane">

                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" name="data[2][step_title_en]" value="<?php echo $this->data[1]['step_title_en']?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>

                    <textarea name="data[2][step_text_en]" rows="3" class="form-control"><?php echo $this->data[1]['step_text_en']?></textarea>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-4">
        <h3>Column 3</h3>

        <ul role="tablist" class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" role="tab" href="#tab_ru_3">ru</a></li>
            <li><a data-toggle="tab" role="tab" href="#tab_en_3">en</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div id="tab_ru_3" class="tab-pane active">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input type="text" name="data[3][step_title]" value="<?php echo $this->data[2]['step_title']?>" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>

                    <textarea name="data[3][step_text]" rows="3" class="form-control"><?php echo $this->data[2]['step_text']; ?></textarea>
                </div>
            </div>
            <div id="tab_en_3" class="tab-pane">
                <div class="form-group form-horizontal">
                    <label>Title</label>

                    <input name="data[3][step_title_en]" value="<?php echo $this->data[2]['step_title_en']?>" type="text" class="form-control">
                </div>
                <div class="form-group form-horizontal">
                    <label>Description</label>

                    <textarea name="data[3][step_text_en]" rows="3" class="form-control"><?php echo $this->data[2]['step_text_en']; ?></textarea>
                </div>
            </div>
        </div>
    </div>
</div>
<button class="btn btn-primary clearfix" type="submit">Save</button>
</form>
