<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>backend</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/style.css"/>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/jquery-1.11.1.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/wysihtml5-0.3.0.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/admin-js.js"></script>
</head>
<body class="page_login">
<div class="container">
    <form class="form-signin" role="form" method="post" action="">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" name="login" class="form-control" placeholder="Login" required="" autofocus="">
        <input type="password" name="password" class="form-control" placeholder="Password" required="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
</body>
</html>