<h1>Press Categories</h1>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->presscats as $presscat) : ?>
            <tr>
                <td><?php echo $presscat['title']; ?> | <?php echo $presscat['title_en']; ?></td>
                <td><?php echo $presscat['status'] == true ? 'enabled' : 'disabled' ?></td>
                <td>
                    <a href="/admin/presscat/edit?id=<?php echo $presscat['id']; ?>" class="btn btn-primary">edit</a>
                    <a href="/admin/presscat/delete?id=<?php echo $presscat['id']; ?>" class="btn btn-danger" <?php echo ($presscat['canDelete'] == false) ? 'disabled="disabled"' : ''; ?> >delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <form action="/admin/presscat/create" method="post">
            <button type="submit" class="btn btn-primary">Add category</button>
        </form>
    </div>
</div>