<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <title><?php echo $this->page['pageTitle']; ?></title>
    <link rel="icon" type="image/png" href="/favicon-32x32.png">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <![endif]-->
    <meta name="robots" content="index, follow"/>
    <meta name="HandheldFriendly" content="True"/>
    <meta name="MobileOptimized" content="320"/>
    <meta name="format-detection" content="telephone=no">
    <meta content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
    <meta name="Keywords" content="<?php echo $this->page['metaKeywords']?>">
    <meta name="Description" content="<?php echo $this->page['metaDescription']?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/style_base.css"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/style_front.css"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/js/lib/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
    <!--[if (lt IE 9) & (!IEMobile)]>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/html5.js"></script>
    <![endif]--> 
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/jquery-1.11.1.js"></script>
<!--    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>-->
<!--    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/fancybox/jquery.fancybox-1.3.4.pack.js"></script>-->
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/jquery.mousewheel-3.0.6.pack.js"></script>
    
     <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/jquery.fancybox.pack.js"></script> 
    
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/fotorama.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/jquery.cycle2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/lib/responsive-nav.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/js.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/getTwit.js"></script>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body class="page">
<div class="outer_wrapper">
    <?php if ($this->action == 'contacts') : ?>
        <?php echo $this->partial('header-contacts'); ?>
    <?php else : ?>
        <?php echo $this->partial('header'); ?>
    <?php endif; ?>
    <div class="structs_wrapper">
        <?php echo $this->content; ?>
    </div>
</div>
<?php echo $this->partial('footer'); ?>
<!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31068716 = new Ya.Metrika({ id:31068716, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/31068716" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64527090-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>